SDE-AE-VoorraadApp/Pages/AB1.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using SDE_AE_VoorraadApp.Data;

namespace SDE_AE_VoorraadApp.Pages
{
    /// <summary>
    /// The AB1Model handler is a handler that was crated as a dummy item for something that we intended to implement if we had the time for it
    /// Being that we never did, this never came up.
    /// </summary>
    public class AB1Model : PageModel
    {
        private readonly LocationContext _context;
        private readonly ILogger<AB1Model> _logger;
        private readonly SignInManager<IdentityUser> _signInManager;

        public AB1Model(SignInManager<IdentityUser> signInManager, ILogger<AB1Model> logger, LocationContext context)
        {
            _context = context;
            _signInManager = signInManager;
            _logger = logger;
        }

        public async Task OnGet()
        {
            await DbUpdater.TwonkUpdate(_context);
        }

    }
}

SDE-AE-VoorraadApp/Pages/AB11.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SDE___Appeltje_Eitje_Automaten___POC_2.Pages
{
    public class AB11Model : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SDE-AE-VoorraadApp/Pages/AR1.cshtml.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using SDE_AE_VoorraadApp.Data;
using SDE_AE_VoorraadApp.Models;

namespace SDE_AE_VoorraadApp.Pages
{
    /// <summary>
    /// Archive display model.
    /// Not accessible  if not logged in.
    /// </summary>
    [Authorize]
    public class AR1Model : PageModel
    {
        /// <summary>
        /// Contains the context of the <see cref="LocationContext"/> Database.
        /// </summary>
        private readonly LocationContext _context;
        private readonly ILogger<AR1Model> _logger;
        private readonly SignInManager<IdentityUser> _signInManager;

        public AR1Model(SignInManager<IdentityUser> signInManager, ILogger<AR1Model> logger, LocationContext context)
        {
            _context = context;
            _signInManager = signInManager;
            _logger = logger;

        }

        public List<OrderList> OrderLocationJoin { get; private set; }

        [BindProperty]
        public DateTime DateTimeRequested { get; set; }

        [BindProperty]
        public int OrderListIDAR1 { get; set; }

        [BindProperty]
        public string WarningMessage { get; set; }

        /// <summary>
        /// Gets all the <see cref="ListRequester.DateTimeOrderList"/> vales and cast them into <see cref="OrderLocationJoin"/>.
        /// </summary>
        public void OnGet(string date)
        {
            DateTimeRequested = date == null ? DateTime.Now : DateTime.Parse(date);

            var orderlist= ListRequester.RequestDateOrderLists(DateTimeRequested, _context);

            if (orderlist.Count == 0)
                WarningMessage = "Er zijn geen lijsten op deze dag aangemaakt";

            OrderLocationJoin = orderlist;
        }

        /// <summary>
        /// Sends redirect request for "AR1_1" with the RouteValue equal of the selected OrderList's ID.
        /// </summary>
        /// <returns>
        /// An <see cref="IActionResult"/>.
        /// </returns>
        public IActionResult OnPost()
        {
            return RedirectToPage("AR1_1", new { List = OrderListIDAR1 });
        }

        public IActionResult OnPostDetermineDate()
        {
            return RedirectToPage("AR1", new { Date = DateTimeRequested });
        }

        /// <summary>
        /// Redirects the user to the Index page.
        /// </summary>
        /// <returns>
        /// An <see cref="IActionResult"/>.
        /// </returns>
        public IActionResult OnPostIndex()
        {
            return RedirectToPage("Index");
        }
    }
}

SDE-AE-VoorraadApp/Pages/AR11.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SDE___Appeltje_Eitje_Automaten___POC_2.Pages
{
    public class AR11Model : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SDE-AE-VoorraadApp/Pages/AR1_1.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using SDE_AE_VoorraadApp.Data;
using SDE_AE_VoorraadApp.Models;

namespace SDE_AE_VoorraadApp.Pages
{
    /// <summary>
    /// Display of archived <see cref="OrderList"/>.
    /// Not accessible if not logged in.
    /// </summary>
    [Authorize]
    public class AR1_1Model : PageModel
    {
        /// <summary>
        /// Contains the context of the <see cref="LocationContext"/> Database.
        /// </summary>
        private readonly LocationContext _context;
        private readonly ILogger<AR1_1Model> _logger;

        public AR1_1Model(ILogger<AR1_1Model> logger, LocationContext context)
        {
            _context = context;
            _logger = logger;
        }

        public OrderList Orders { get; set; }
        public List<ListRequester.OrderLocationJoin> OrderLocationJoin { get; private set; }
        public List<ListRequester.OrderLocationJoin> LocationPriority { get; private set; }

        /// <summary>
        /// Receives a string from <see cref="AR1Model.OnPost"/> and uses this to display the correct OrderList.
        /// </summary>
        /// <param name="action">
        /// The value passed by <see cref="AR1Model.OnPost"/>.
        /// </param>
        public void OnGet(string list)
        {
            // Parse the string value into an int.
            var orderListId = int.Parse(list);
            _logger.LogInformation($"{orderListId} was successfully created");

            // Use the orderListId in order to get the full list.
            // Create a new list by sorting them by Priority.
            var orderLocation = ListRequester.RequestDateOrderList(_context, orderListId);
            _logger.LogInformation($"{orderLocation} was successfully created");

            OrderLocationJoin = orderLocation;
            LocationPriority = orderLocation.OrderByDescending(ol => ol.Priority).ToList();
            Orders = _context.OrderLists.ToList().Find(ol => ol.ID.Equals(orderListId));
        }

        /// <summary>
        /// Redirects the user to the Index page.
        /// </summary>
        /// <returns>
        /// An <see cref="IActionResult"/>.
        /// </returns>
        public IActionResult OnPostIndex()
        {
            return RedirectToPage("Index");
        }
    }
}

SDE-AE-VoorraadApp/Pages/CF1.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SDE_AE_VoorraadApp.Pages
{
    /// <summary>
    /// The CF1Model handler is a handler that was crated as a dummy item for something that we intended to implement if we had the time for it
    /// Being that we never did, this never came up.
    /// </summary>
    [Authorize]
    public class CF1Model : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SDE-AE-VoorraadApp/Pages/CF11.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SDE___Appeltje_Eitje_Automaten___POC_2.Pages
{
    public class CF11Model : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SDE-AE-VoorraadApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;

namespace SDE_AE_VoorraadApp.Pages
{
    /// <summary>
    /// Custom 404 page.
    /// </summary>
    [Authorize]
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

SDE-AE-VoorraadApp/Pages/Index.cshtml.cs
using System.Diagnostics.Eventing.Reader;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using SDE_AE_VoorraadApp.Data;

namespace SDE_AE_VoorraadApp.Pages
{
    /// <summary>
    /// Handler of the index page.
    /// </summary>
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly LocationContext _context;


        public IndexModel(SignInManager<IdentityUser> signInManager, ILogger<IndexModel> logger, LocationContext context)
        {
            _signInManager = signInManager;
            _logger = logger;
            _context = context;
        }

        public void OnGet()
        {

        }

        /// <summary>
        /// A handler to redirect the user to the LG1 page.
        /// </summary>
        /// <returns>
        /// An <see cref="IActionResult"/>.
        /// </returns>
        public IActionResult OnPostLG1()
        {
            return RedirectToPage("LG1");
        }

        /// <summary>
        /// A handler to redirect the user to the AR1 page.
        /// </summary>
        /// <returns>
        /// An <see cref="IActionResult"/>.
        /// </returns>
        public IActionResult OnPostAR1()
        {
            return RedirectToPage("AR1");
        }

        /// <summary>
        /// A handler to redirect the user to the AB1 page.
        /// The handler does currently work but is not actively in use.
        /// </summary>
        /// <returns>
        /// An <see cref="IActionResult"/>.
        /// </returns>
        public IActionResult OnPostAB1()
        {
            return RedirectToPage("AB1");
        }

        /// <summary>
        /// A handler to redirect the user to the CF1 page.
        /// The handler does currently work but is not actively in use.
        /// </summary>
        /// <returns>
        /// An <see cref="IActionResult"/>.
        /// </returns>
        public IActionResult OnPostCF1()
        {
            return RedirectToPage("CF1");
        }

        /// <summary>
        /// Custom logout function that signs out the user asynchronous and redirects them to the Login screen.
        /// </summary>
        /// <returns>
        /// An <see cref="IActionResult"/>.
        /// </returns>
        public async Task<IActionResult> OnPostLogout()
        {
            await _signInManager.SignOutAsync();
            _logger.LogInformation("User logged out.");
            return LocalRedirect("~/Login");
        }
        
        public async Task<IActionResult> OnPostTwonkReload()
        {
            await DbUpdater.TwonkUpdate(_context);
            return LocalRedirect("~/Index");
        }
    }
}

SDE-AE-VoorraadApp/Pages/LG1.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SDE_AE_VoorraadApp.Data;
using SDE_AE_VoorraadApp.Models;

namespace SDE_AE_VoorraadApp.Pages
{
    /// <summary>
    /// Main menu handler for creating an OrderList.
    /// </summary>
    [Authorize]
    public class LG1Model : PageModel
    {
        private readonly LocationContext _context;
        private readonly ILogger<LG1Model> _logger;
        private readonly SignInManager<IdentityUser> _signInManager;

        public LG1Model(SignInManager<IdentityUser> signInManager, ILogger<LG1Model> logger, LocationContext context)
        {
            _context = context;
            _signInManager = signInManager;
            _logger = logger;
        }

        [BindProperty]
        public List<int> LocationToPrint { get; set; }

        public IList<Location> Location { get; set; }

        /// <summary>
        /// Fires a <see cref="DbUpdater.TwinkUpdate"/> and loads all locations in the <see cref="LocationContext"/> Database.
        /// </summary>
        /// <returns>
        /// A <see cref="Task"/>.
        /// </returns>
        public async Task OnGetAsync()
        {
            var result = await DbUpdater.TwinkUpdate(_context);
            if (result > 0)
            {
                _logger.LogInformation($"{result} lines were updated!!!");
            }
            Location = await _context.Locations.ToListAsync();
        }

        /// <summary>
        /// Creates the list from the selected <see cref="LocationToPrint"/>.
        /// </summary>
        public async Task<IActionResult> OnPostLG1_1()
        {
            // Being that the select all button has an ID of 0 the function checks if that values is among the list.
            // If so all locations get loading into the ListRequester.CreateList input.
            // After the list has finished creating, if the total amount of lines affect is greater then 0 the list will get show.
            // if this is not the case however it is seen as a duplicate request and get send to the "ListDupe" page.
            var rad = await ListRequester.CreateList(_context, LocationToPrint.Contains(0) ? _context.Locations.ToList().Select(l => l.ID): LocationToPrint);
            return RedirectToPage(rad > 0 ? "LG1_1" : "ListDupe");
        }
    }
}

SDE-AE-VoorraadApp/Pages/LG11.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SDE_AE_VoorraadApp.Models;

namespace SDE___Appeltje_Eitje_Automaten___POC_2.Pages
{
    public class LG11Model : PageModel
    {
        private readonly SDE_AE_VoorraadApp.Data.LocationContext _context;
        public LG11Model(SDE_AE_VoorraadApp.Data.LocationContext context)
        {
            _context = context;
        }

        public IList<Location> Location { get; set; }

        public async Task OnGetAsync()
        {
            Location = await _context.Locations.ToListAsync();
        }
    }
}

SDE-AE-VoorraadApp/Pages/LG1_1.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using SDE_AE_VoorraadApp.Data;
using SDE_AE_VoorraadApp.Models;

namespace SDE_AE_VoorraadApp.Pages
{
    /// <summary>
    /// Display of most recently created <see cref="OrderList"/>.
    /// Not accessible if not logged in.
    /// </summary>
    [Authorize]
    public class LG1_1Model : PageModel
    {
        /// <summary>
        /// Contains the context of the <see cref="LocationContext"/> Database.
        /// </summary>
        private readonly LocationContext _context;
        private readonly ILogger<LG1_1Model> _logger;

        public LG1_1Model(ILogger<LG1_1Model> logger, LocationContext context)
        {
            _context = context;
            _logger = logger;
        }

        public OrderList Orders { get; set; }
        public List<ListRequester.OrderLocationJoin> OrderLocationJoin { get; private set; }
        public List<ListRequester.OrderLocationJoin> LocationPriority { get; private set; }

        /// <summary>
        /// Gets the most recent <see cref="OrderList"/> created and loads that in the appropriate variables.
        /// </summary>
        public void OnGet()
        {
            var orderLocation = ListRequester.RequestRecentList(_context);
            OrderLocationJoin = orderLocation;
            LocationPriority = orderLocation.OrderByDescending(ol => ol.Priority).ToList();
            Orders = _context.OrderLists.ToList().Last();
        }

        /// <summary>
        /// Redirects the user to the Index page.
        /// </summary>
        /// <returns>
        /// An <see cref="IActionResult"/>.
        /// </returns>
        public IActionResult OnPostIndex()
        {
            return RedirectToPage("Index");
        }
    }
}

SDE-AE-VoorraadApp/Pages/ListDupe.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SDE_AE_VoorraadApp.Pages
{
    [Authorize]
    public class ListDupeModel : PageModel
    {
        public void OnGet()
        {
        }
        
        public IActionResult OnPostIndex()
        {
            return RedirectToPage("Index");
        }
    }
}

SDE-AE-VoorraadApp/Pages/AB1.cshtml
@page
@model SDE_AE_VoorraadApp.Pages.AB1Model
@{
    ViewData["Title"] = "Accounts Beheren";
}

@section Styles {
    <link rel="stylesheet" href="~/css/desktop.css" />
    <link rel="stylesheet" href="~/css/mobile.css" />
}
<!DOCTYPE html>
<head>

</head>

<body>
    <!-- ################################################################### -->
    <!-- Deze pagina viel buiten het MVP en is dus niet verder doorontwikkeld-->
    <!-- ################################################################### -->

    <div>
        <form asp-page="Index" method="post">
            <input type="image" src="~/Home.png" alt="Home" class="home">
        </form>
    </div>

    <div>
        <form asp-page="Index" asp-page-handler="Logout" method="post">
            <input type="image" src="~/LogUit.png" alt="Log Uit" class="logOut">
        </form>
    </div>

    <div>
        <input type="image" onclick="history.go(-1)" src="~/Terug.png" alt="Terug" class="back">
    </div>

    <div>
        <img src="~/Logo-AE.png" alt="Logo Appeltje Eitje Automaten" class="aeLogo">
    </div>

    <div class="placeholderTitel">
        Buiten MVP:<br>Accounts Beheren
    </div>
</body>

SDE-AE-VoorraadApp/Pages/AR1.cshtml
@page
@model SDE_AE_VoorraadApp.Pages.AR1Model
@{
    ViewData["Title"] = "Archief";
}

@section Styles {
    <link rel="stylesheet" href="~/css/desktop.css" />
    <link rel="stylesheet" href="~/css/mobile.css" />
}

<!DOCTYPE html>
<head>

</head>

<body>
    <div>
        <form asp-page="Index" method="post">
            <input type="image" src="~/Home.png" alt="Home" class="home">
        </form>
    </div>

    <div>
        <form asp-page="Index" asp-page-handler="Logout" method="post">
            <input type="image" src="~/LogUit.png" alt="Log Uit" class="logOut">
        </form>
    </div>

    <div>
        <input type="image" onclick="history.go(-1)" src="~/Terug.png" alt="Terug" class="back">
    </div>

    <div>
        <img src="~/Logo-AE.png" alt="Logo Appeltje Eitje Automaten" class="aeLogo">
    </div>

    <div>
        <div class="dateSelector">
            <form asp-page-handler="DetermineDate" method="POST">
                <input type="date" name="DateTimeRequested" asp-for="DateTimeRequested">
                <button type="submit"></button>
            </form>
        </div>

        <script type="text/javascript">
            function retrieveDate() {
                var dateStr = document.getElementById("dateInput").value;
                var dateStr2 = new Date(dateStr);

                console.log(dateStr);
                console.log(dateStr2);
            }
        </script>

        <div class="listBorder">
            <div>
                <div class="archiveDateTitle">
                    @Html.DisplayFor(modelItem => modelItem.WarningMessage)
                    @foreach (var orderList in Model.OrderLocationJoin)
                    {
                        <div>
                            <form asp-page="AR1" method="POST">
                                <button asp-for class="invisButton" name="orderListIDAR1" value="@Html.DisplayFor(modelItem => orderList.ID)">@Html.DisplayFor(modelItem => orderList.Name)</button><br>
                            </form>
                        </div>
                    }
                    <br><br>
                </div>

            </div>
        </div>
    </div>
</body>

SDE-AE-VoorraadApp/Pages/CF1.cshtml
@page
@model SDE_AE_VoorraadApp.Pages.CF1Model
@{
    ViewData["Title"] = "Couriers & Filialen";
}

@section Styles {
    <link rel="stylesheet" href="~/css/desktop.css" />
    <link rel="stylesheet" href="~/css/mobile.css" />
}

<!DOCTYPE html>
<head>

</head>

<body>
    <!-- ################################################################### -->
    <!-- Deze pagina viel buiten het MVP en is dus niet verder doorontwikkeld-->
    <!-- ################################################################### -->

    <div>
        <form asp-page="Index" method="post">
            <input type="image" src="~/Home.png" alt="Home" class="home">
        </form>
    </div>

    <div>
        <form asp-page="Index" asp-page-handler="Logout" method="post">
            <input type="image" src="~/LogUit.png" alt="Log Uit" class="logOut">
        </form>
    </div>

    <div>
        <input type="image" onclick="history.go(-1)" src="~/Terug.png" alt="Terug" class="back">
    </div>

    <div>
        <img src="~/Logo-AE.png" alt="Logo Appeltje Eitje Automaten" class="aeLogo">
    </div>

    <div class="placeholderTitel">
        Buiten MVP:<br>Couriers & Filialen
    </div>
</body>

SDE-AE-VoorraadApp/Pages/Index.cshtml
@page
@model SDE_AE_VoorraadApp.Pages.IndexModel
@{
    ViewData["Title"] = "Home Page";
}

@section Styles {
    <link rel="stylesheet" href="~/css/desktop.css" />
    <link rel="stylesheet" href="~/css/mobile.css" />
}

<!DOCTYPE html>
<head>

</head>

<body>
<div>
    <form asp-page="Index" asp-page-handler="Logout" method="post">
        <input type="image" src="~/LogUit.png" alt="Log Uit" class="logOut">
    </form>
</div>

<div>
    <form asp-page-handler="TwonkReload" method="post">
        <input type="image" src="~/Refresh.png" alt="Refresh Database" class="refresh">
    </form>
</div>

<div>
    <img src="~/Logo-AE.png" alt="Logo Appeltje Eitje Automaten" class="aeLogo">
</div>

<!-- KNOP 1: Lijst Genereren -->
<form method="POST" asp-page="Index">
    <input type="submit" asp-page-handler="LG1" value="Lijst Genereren" class="hp-Button-Inherit hp-Button1">
</form>

<!-- KNOP 2: Archief -->
<form method="POST" asp-page="Index">
    <input type="submit" asp-page-handler="AR1" value="Archief" class="hp-Button-Inherit hp-Button2">
</form>

<!-- KNOP 3: Accounts Beheren -->
<!-- Gezet op input type=hidden omdat deze knop buiten het MVP viel en niet binnen de gespecificieerde tijd ontwikkeld konden worden -->
<form method="POST" asp-page="Index">
    <input type="hidden" asp-page-handler="AB1" value="Accounts Beheren" class="hp-Button-Inherit hp-Button3">
</form>

<!-- KNOP 4: Couriers & Filialen -->
<!-- Gezet op input type=hidden omdat deze knop buiten het MVP viel en niet binnen de gespecificieerde tijd ontwikkeld konden worden -->
<form method="POST" asp-page="Index">
    <input type="hidden" asp-page-handler="CF1" value="Couriers & Filialen" class="hp-Button-Inherit hp-Button4">
</form>
</body>

SDE-AE-VoorraadApp/Pages/LG1.cshtml
@page
@model SDE_AE_VoorraadApp.Pages.LG1Model
@{
    ViewData["Title"] = "Filiaal Selecteren";
}

@section Styles {
    <link rel="stylesheet" href="~/css/desktop.css" />
    <link rel="stylesheet" href="~/css/mobile.css" />
}

<!DOCTYPE html>
<head>

</head>

<body>
    <div>
        <form asp-page="Index" method="post">
            <input type="image" src="~/Home.png" alt="Home" class="home">
        </form>
    </div>

    <div>
        <form asp-page="Index" asp-page-handler="Logout" method="post">
            <input type="image" src="~/LogUit.png" alt="Log Uit" class="logOut">
        </form>
    </div>

    <div>
        <input type="image" onclick="history.go(-1)" src="~/Terug.png" alt="Terug" class="back">
    </div>

    <div>
        <img src="~/Logo-AE.png" alt="Logo Appeltje Eitje Automaten" class="aeLogo">
    </div>

    <div class="filiaalSelector">
        <form method="POST" asp-page="LG1">
            <label for="filialen" id="checkBoxTitel"><b>Filialen:</b></label><br>
            <div class="checkboxCenter">
                <div class="checkAll">
                    <input type="checkbox" name="LocationToPrint" value="0" onClick="toggle(this)"> Selecteer alle filialen<br><br>
                </div>

                <script type="text/javascript">
                    function toggle(source) {
                        checkboxes = document.getElementsByName('LocationToPrint');
                        for (var i = 0, n = checkboxes.length; i < n; i++) {
                            checkboxes[i].checked = source.checked;
                        }
                    }
                </script>

                <div class="checkOthers">
                    @foreach (var item in Model.Location)
                    {
                        <div class="fontSize">
                            <input type="checkbox" name="LocationToPrint" value="@item.ID">
                            @Html.DisplayFor(modelItem => item.Place) - @Html.DisplayFor(modelItem => item.City)
                        </div>
                    }
                </div>
                <br>
                <input type="submit" class="generateList" asp-page-handler="LG1_1" value="Genereer lijst">
            </div>
        </form>
    </div>
</body>

SDE-AE-VoorraadApp/Pages/ListDupe.cshtml
@page
@model SDE_AE_VoorraadApp.Pages.ListDupeModel
@{
    ViewData["Title"] = "Filiaal Selecteren";
}

@section Styles {
    <link rel="stylesheet" href="~/css/desktop.css" />
    <link rel="stylesheet" href="~/css/mobile.css" />
}

<!DOCTYPE html>
<head>

</head>

<body>
    <div>
        <img src="~/Logo-AE.png" alt="Logo Appeltje Eitje Automaten" class="aeLogo">
    </div>

    <div class="returnHome2">
        <div class="textMiddle">
            U wordt teruggestuurd naar de Home Page omdat u een lijst probeerde aan te maken die al gegenereerd is.<br><br>
            Als u alsnog een lijst wilt creeëren, zorgt u er dan voor dat u een unieke selectie bij de filialen maakt.
        </div>

        <div>
            <form method="POST" asp-page="ListDupe">
                <input type="submit" asp-page-handler="Index" value="Terug naar Home" class="returnHome">
            </form>
        </div>
    </div>
</body>

SDE-AE-VoorraadApp/Pages/Login.cshtml
@page
@model SDE_AE_VoorraadApp.Pages.LoginModel
@{
    ViewData["Title"] = "Login";
}

@section Styles {
    <link rel="stylesheet" href="~/css/desktop.css" />
    <link rel="stylesheet" href="~/css/mobile.css" />
}

<!DOCTYPE html>
<head>

</head>

<body>
<div>
    <img src="~/Logo-AE.png" alt="Logo Appeltje Eitje Automaten" class="aeLogo"><br><br>
</div>

<div class="form">
    <form method="post">
        <div asp-validation-summary="All"></div>
        <div class="form-group">
            <label asp-for="Input.Email" id="textFieldTitel"></label><br>
            <input asp-for="Input.Email" type="text" id="loginField" placeholder="Vul uw gebruikersnaam in..."/>
            
        </div>
        <br><br><br>
        <div class="form-group">
            <label asp-for="Input.Password" id="textFieldTitel"></label><br>
            <input asp-for="Input.Password" id="loginField" placeholder="Vul uw wachtwoord in..."/>
            
        </div>
        <br><br><br>
        <div class="form-group">
            <div class="checkbox">
                <label asp-for="Input.RememberMe">
                    <input asp-for="Input.RememberMe" />
                    @Html.DisplayNameFor(m => m.Input.RememberMe)
                </label>
            </div>
        </div>
        <div class="form-group">
            <button type="submit" class="logIn">Log in</button>
        </div>
    </form>
</div>
</body>